# Generated by Django 3.2 on 2021-04-10 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('stu_id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学号')),
                ('cf_id', models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='CF账号')),
                ('nickname', models.CharField(max_length=24, verbose_name='昵称')),
                ('need_peer', models.BooleanField(default=False, verbose_name='是否需要队友')),
                ('avatar_key', models.CharField(default='avatar/default_customer', max_length=48, verbose_name='头像key')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '队员',
                'verbose_name_plural': '队员',
            },
            managers=[
                ('objects', person.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='训练日期')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='队员')),
            ],
            options={
                'verbose_name': '训练日期',
                'verbose_name_plural': '训练日期',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='板块名')),
                ('users', models.ManyToManyField(related_name='regions', to=settings.AUTH_USER_MODEL, verbose_name='队员')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
            },
        ),
        migrations.CreateModel(
            name='Contirbute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='主题')),
                ('contri_type', models.CharField(choices=[('VO', '志愿'), ('CL', '清理'), ('TE', '教学'), ('QS', '出题'), ('OT', '其他')], max_length=2, verbose_name='分类')),
                ('description', models.CharField(max_length=30, verbose_name='描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='队员')),
            ],
            options={
                'verbose_name': '贡献',
                'verbose_name_plural': '贡献',
            },
        ),
    ]
